OJ-924: Save client ip address provided to /session API call
alphagov/di-ipv-cri-common-lambdas pull request #32
Opened 2022-09-14 10:20 UTC by praveen-gds

## Proposed changes

### What changed

### Why did it change

### Issue tracking

- [KBV-XXXX](https://govukverify.atlassian.net/browse/KBV-XXX)

## Checklists

### Environment variables or secrets

- [ ] No environment variables or secrets were added or changed

- [ ] Documented in the [README](./blob/main/README.md)
- [ ] Added to deployment repository
- [ ] Added to local startup repository

### Other considerations

- [ ] Update [README](./blob/main/README.md) with any new instructions or tasks

2022-09-21 15:04 UTC, techaman-m commented on session/src/test/java/uk/gov/di/ipv/cri/common/api/handler/SessionHandlerTest.java
> +//        requestHeaders.put("X-Forwarded-For", "192.0.2.0");
Can we remove this commented line if it is not required?

2022-09-22 07:51 UTC, idrop commented on session/src/test/java/uk/gov/di/ipv/cri/common/api/handler/SessionHandlerTest.java
>          String clientSessionId = "govuk_signin_journey_id_value";
can you verify that the sessionRequest has been set with the client ip address please? i.e.
`verify(sessionRequest).setClientIpAddress("the ip address");`

2022-09-22 07:53 UTC, idrop requested changes
Added one extra verification to do or debate @praveen-gds

2022-09-22 08:54 UTC, idrop submitted a review, later dismissed

2022-09-22 09:05 UTC, jkunle submitted a review, later dismissed

2022-09-22 09:14 UTC, techaman-m submitted a review, later dismissed

2022-09-22 09:14 UTC, techaman-m commented on session/src/test/java/uk/gov/di/ipv/cri/common/api/handler/SessionHandlerTest.java
> +        verify(sessionRequest).setClientIpAddress("192.0.2.0");
Should it be 
`verify(sessionRequest).getClientIpAddress("192.0.2.0");`

2022-09-22 09:26 UTC, techaman-m approved these changes

2022-09-22 09:33 UTC, praveen-gds commented
Closing this PR as I created new PR https://github.com/alphagov/di-ipv-cri-common-lambdas/pull/39> as this PR has some sign commit issues.

2022-09-22 09:33 UTC, closed without merging