OJ-997 - Added new integration test for session endpoint
alphagov/di-ipv-cri-common-lambdas pull request #53
Opened 2022-10-11 16:45 UTC by techaman-m

## Proposed changes

### What changed
We have created a happy case scenario to test session endpoint

### Why did it change

This test will act as a QA gateway.

### Issue tracking
 
https://govukverify.atlassian.net/browse/OJ-997
## Checklists

### Environment variables or secrets

STACK_NAME=di-ipv-cri-xxx 
API_GATEWAY_ID_PRIVATE=xxx 
IPV_CORE_STUB_BASIC_AUTH_USER=xxx 
IPV_CORE_STUB_BASIC_AUTH_PASSWORD=xxx 
IPV_CORE_STUB_URL="https://di-ipv-core-stub.london.cloudapps.digital" 

### To run the test

`STACK_NAME=di-ipv-cri-xxx  API_GATEWAY_ID_PRIVATE=xxx  IPV_CORE_STUB_BASIC_AUTH_USER=xxx IPV_CORE_STUB_BASIC_AUTH_PASSWORD=xxx IPV_CORE_STUB_URL="https://di-ipv-core-stub.london.cloudapps.digital"  gradle cucumber -P tags=@session_endpoint_pre_merge_happy`

2022-10-13 09:06 UTC, tal-nagra requested changes

2022-10-13 09:06 UTC, tal-nagra commented on integration-tests/src/test/java/gov/uk/di/ipv/cri/common/api/stepDefinitions/SessionEndpointSteps.java
> +                IpvCoreStubUtil.getClaimsForUser(ipvCoreStubURL, experianRowNumber);
remove the ipvCoreStubURL method parameter & simply pass the experianRowNumber to the getClaimsForUser method

2022-10-13 09:06 UTC, tal-nagra commented on integration-tests/src/test/java/gov/uk/di/ipv/cri/common/api/stepDefinitions/SessionEndpointSteps.java
> +        response = IpvCoreStubUtil.sendHttpRequest(request);
add a new method to the IpvCoreStubUtil entitled sendSessionRequest and pass in the sessionRequestBody

2022-10-13 09:06 UTC, tal-nagra commented on integration-tests/src/test/java/gov/uk/di/ipv/cri/common/api/stepDefinitions/SessionEndpointSteps.java
> +        var request =
remove lines 40-49

2022-10-13 09:06 UTC, tal-nagra commented on integration-tests/src/test/java/gov/uk/di/ipv/cri/common/api/util/IpvCoreStubUtil.java
> +    public static String getPrivateAPIEndpoint() {
make this method private

2022-10-13 09:06 UTC, tal-nagra commented on integration-tests/src/test/java/gov/uk/di/ipv/cri/common/api/util/IpvCoreStubUtil.java
> +        Optional.ofNullable(apiEndpoint).orElseThrow(() -> new IllegalArgumentException(message));
remove the second `message` argument from this method.
In the IllegalArgumentException constructor pass in something along the lines of 
String.format("Environment variable %s is not assigned", apikey)

2022-10-13 09:06 UTC, tal-nagra commented on integration-tests/src/test/java/gov/uk/di/ipv/cri/common/api/util/IpvCoreStubUtil.java
> +    public static HttpResponse<String> sendHttpRequest(HttpRequest request)
make this method `private`

2022-10-13 09:06 UTC, tal-nagra commented on integration-tests/src/test/java/gov/uk/di/ipv/cri/common/api/util/IpvCoreStubUtil.java
> +    public static String getIPVCoreStubURL() {
make this method private

2022-10-13 09:06 UTC, tal-nagra commented on integration-tests/src/test/java/gov/uk/di/ipv/cri/common/api/util/IpvCoreStubUtil.java
> +    public static String createRequest(String baseUrl, String jsonString)
remove the baseUrl parameter & rename this method to sendCreateSessionRequest

2022-10-13 13:07 UTC, tal-nagra submitted a review, later dismissed
Any further re-factoring etc can be tackled in a future PR

2022-10-17 08:49 UTC, idrop approved these changes

2022-10-17 10:03 UTC, merged