OJ-1014: Add Access Token integration test
alphagov/di-ipv-cri-common-lambdas pull request #61
Opened 2022-10-28 12:35 UTC by techaman-m

### Requirement
Add cucumber integration test to the `di-ipv-cri-common-lambdas` for `access token` end point

### Important considerations:
- It is imperative to call the `session` and `authorization` end points before invoking the `access token` end point

### What changed
- Added new `feature` file for Access Token end point
- New steps added to the `APISteps` file

### Issue tracking

- [OJ-1014](https://govukverify.atlassian.net/browse/OJ-1014)

### Other considerations
To run the tests:

`STACK_NAME=di-ipv-cri-address-api-aman API_GATEWAY_ID_PRIVATE=y7goqr35n8 API_GATEWAY_ID_PUBLIC=ijy6basnvk IPV_CORE_STUB_BASIC_AUTH_USER=user IPV_CORE_STUB_BASIC_AUTH_PASSWORD=qTdrBchPGyt2bxaCr3ve IPV_CORE_STUB_URL="https://di-ipv-core-stub.london.cloudapps.digital" APIGW_API_KEY=vNcGwyTEkz6gMxP4pfASQ9IACaX3SkLq5WKqDpJc gradle integration-tests:cucumber`

2022-11-01 09:13 UTC, gokhakan submitted a review, later dismissed

2022-11-01 10:05 UTC, tal-nagra requested changes

2022-11-01 10:05 UTC, tal-nagra commented on integration-tests/src/test/java/gov/uk/di/ipv/cri/common/api/stepDefinitions/APISteps.java
> +        String privateKeyJWT = getPrivateKeyJWT(authorizationCode);
move all the logic from lines 183-196 into the IpvCoreStubUtil class

2022-11-01 10:05 UTC, tal-nagra commented on integration-tests/src/test/java/gov/uk/di/ipv/cri/common/api/stepDefinitions/APISteps.java
> +                IpvCoreStubUtil.sendAccessTokenRequest(
change this method invocation to just pass `"wrong_authorization_code"`

2022-11-01 10:05 UTC, tal-nagra commented on integration-tests/src/test/java/gov/uk/di/ipv/cri/common/api/util/IpvCoreStubUtil.java
> +    public static String getPrivateKeyJWT(String authorizationCode)
change the access modifier to `private`

2022-11-01 10:05 UTC, tal-nagra commented on integration-tests/src/test/java/gov/uk/di/ipv/cri/common/api/util/IpvCoreStubUtil.java
> +            String devAccessTokenUri, String privateKeyJWT)
Change this method to receive a String `authorizationCode` rather than `privateKeyJWT`
This class should deal with the creation of the privateKeyJWT

2022-11-01 10:05 UTC, tal-nagra commented on integration-tests/src/test/resources/features/AccessTokenAPI.feature
> +    And a "Access token expired" error with code 1026 is sent in the response
add new line to the end of this file

2022-11-02 12:08 UTC, tal-nagra requested changes

2022-11-02 12:08 UTC, tal-nagra commented on integration-tests/src/test/java/gov/uk/di/ipv/cri/common/api/stepDefinitions/APISteps.java
> +    private String authorizationCode;
let's rename this to `currentAuthorizationCode` so that it matches the naming convention used for `currentSessionId`

2022-11-02 12:08 UTC, tal-nagra commented on integration-tests/src/test/java/gov/uk/di/ipv/cri/common/api/util/IpvCoreStubUtil.java
> +                                        .setPath(DEV_ACCESS_TOKEN_URI)
change this line to `.setPath("/dev/token")`

2022-11-02 12:08 UTC, tal-nagra commented on integration-tests/src/test/java/gov/uk/di/ipv/cri/common/api/util/IpvCoreStubUtil.java
> +                                        String.format(
Remove the `String.format` here simply pass the string "PUBLIC_API_KEY environment variable is not assigned" to the `IllegalArgumentException` constructor

2022-11-02 12:59 UTC, tal-nagra approved these changes

2022-11-02 13:05 UTC, merlinc approved these changes

2022-11-02 13:06 UTC, merged